import type { ServerBuild } from 'react-router';
import { createPagesFunctionHandler } from '@react-router/cloudflare';

// @ts-ignore because the server build file is generated by `react-router build`
import * as serverBuild from '../build/server';

export const onRequest = createPagesFunctionHandler({
  build: serverBuild as unknown as ServerBuild,
});
